trigger:
- main
- feature/*

pool:
  name: Default

stages:
  - stage: TerraformPlan
    displayName: terraform init, validate and plan
    jobs:
      - job: Terraform
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AZ-ADO-Connection'
              backendAzureRmResourceGroupName: 'rgstatefile'
              backendAzureRmStorageAccountName: 'stgstatefile2'
              backendAzureRmContainerName: 'statecontainer'
              backendAzureRmKey: 'restart.tfstate'


